[package]
name     = "stackk"
version  = "0.1.0"
resolver = "2"
edition  = "2021"

[profile.release]
codegen-units = 1
lto           = true

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde  = { version = "1.0", features = ["derive"] }

[features]
dot_env = []
