version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  lint_and_build:
    jobs:
      - lint_only:
            filters:
                  branches:
                        ignore:
                            - master
                            - project
      - build_only:
            filters:
                  branches:
                        ignore:
                            - master
                            - project
      - cloc:
            filters:
                  branches:
                        ignore:
                            - master
                            - project
      - approve-build-for-test:
            type: approval
            filters:
                  branches:
                        ignore:
                            - master
                            - project
      - deploy_test:
            requires:
                  - lint_only
                  - build_only
                  - cloc
                  - approve-build-for-test
            filters:
                  branches:
                        ignore:
                            - master
                            - project

  build_for_test:
      jobs:
      - lint_only:
            filters:
                  branches:
                        only: project

      - deploy_test:
            requires:
                  - lint_only
            filters:
                  branches:
                        only: project

  build_for_prod:
      jobs:
      - deploy_prod:
            filters:
                  tags:
                        only: /[Vv]([0-9]{1,2}\.){2}[0-9]+/
                  branches:
                        ignore: /.*/

jobs:
  cloc:
    docker:
        - image: circleci/node:12.18.3
    working_directory: ~/repo
    steps:
        - checkout
        - run:
              name: Count
              command: npx cloc src

  lint_only:
    docker:
        - image: circleci/node:12.18.3
    working_directory: ~/repo
    steps:
        - checkout
        - run:
              name: Install Dependencies
              command: npm ci
        - run:
              name: Run Linter
              command: npm run lint

  build_only:
        docker:
              - image: circleci/node:12.18.3
        working_directory: ~/repo
        steps:
              - checkout
              - run:
                    name: Install Dependencies
                    command: npm ci
              - run:
                    name: Build
                    command: API_KEY="$API_KEY_TEST" AUTH_DOMAIN="$AUTH_DOMAIN_TEST" PROJECT_ID="$PROJECT_ID_TEST" STORAGE_BUCKET="$STORAGE_BUCKET_TEST" MESSAGE_SENDER_ID="$MESSAGE_SENDER_ID_TEST" APP_ID="$APP_ID_TEST" npm run build

  deploy_test:
      docker:
            - image: circleci/node:12.18.3
      working_directory: ~/repo
      steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: npm ci
            - run:
                  name: Deploy Test
                  command: API_KEY="$API_KEY_TEST" AUTH_DOMAIN="$AUTH_DOMAIN_TEST" PROJECT_ID="$PROJECT_ID_TEST" STORAGE_BUCKET="$STORAGE_BUCKET_TEST" MESSAGE_SENDER_ID="$MESSAGE_SENDER_ID_TEST" APP_ID="$APP_ID_TEST" APP_VERSION="test-$CIRCLE_BUILD_NUM" npm run deploy:test

  deploy_prod:
      docker:
            - image: circleci/node:12.18.3
      working_directory: ~/repo
      steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: npm ci
            - run:
                  name: Run Linter
                  command: npm run lint
            - setup_remote_docker:
                  version: 20.10.7
            - run:
                  name: Docker Login
                  command: docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                  name: Build Assets
                  command: API_KEY="$API_KEY" AUTH_DOMAIN="$AUTH_DOMAIN" PROJECT_ID="$PROJECT_ID" STORAGE_BUCKET="$STORAGE_BUCKET" MESSAGE_SENDER_ID="$MESSAGE_SENDER_ID" APP_ID="$APP_ID" APP_VERSION="$CIRCLE_TAG" npm run build
            - run:
                  name: Build Container
                  command: docker build -t watsom27/stackk:$CIRCLE_TAG .
            - run:
                  name: Push To Repository
                  command: docker push watsom27/stackk:$CIRCLE_TAG
            - run:
                  name: Firebase Deploy (Legacy)
                  command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting -m "$CIRCLE_TAG"
