version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  lint_and_build:
    jobs:
      - lint_only:
            filters:
                  branches:
                        ignore:
                            - master
                            - project
      - build_only:
            filters:
                  branches:
                        ignore:
                            - master
                            - project
      - cloc:
            filters:
                  branches:
                        ignore:
                            - master
                            - project

  build_for_test:
      jobs:
      - lint_only:
            filters:
                  branches:
                        only: project

      - deploy_test:
            requires:
                  - lint_only
            filters:
                  branches:
                        only: project

  build_for_prod:
      jobs:
      - lint_only:
            filters:
                  tags:
                        only: /[Vv]([0-9]{1,2}\.){2}[0-9]+/
                  branches:
                        ignore: /.*/
      - deploy_prod:
            requires:
                  - lint_only

            filters:
                  tags:
                        only: /[Vv]([0-9]{1,2}\.){2}[0-9]+/
                  branches:
                        ignore: /.*/

jobs:
  cloc:
    docker:
        - image: circleci/node:12.18.3
    working_directory: ~/repo
    steps:
        - checkout
        - run:
              name: Count
              command: npx cloc src

  lint_only:
    docker:
        - image: circleci/node:12.18.3
    working_directory: ~/repo
    steps:
        - checkout
        - run:
              name: Install Dependencies
              command: npm ci
        - run:
              name: Run Linter
              command: npm run lint

  build_only:
        docker:
              - image: circleci/node:12.18.3
        working_directory: ~/repo
        steps:
              - checkout
              - run:
                    name: Install Dependencies
                    command: npm ci
              - run:
                    name: Build
                    command: DB="$DB_CONFIG" npm run build

  deploy_test:
      docker:
            - image: circleci/node:12.18.3
      working_directory: ~/repo
      steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: npm ci
            - run:
                  name: Deploy Test
                  command: DB="$DB_CONFIG" npm run deploy:test

  deploy_prod:
      docker:
            - image: circleci/node:12.18.3
      working_directory: ~/repo
      steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: npm ci
            - run:
                  name: Build
                  command: DB="$DB_CONFIG" npm run build
            - run:
                  name: Firebase Deploy
                  command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting -m "$CIRCLE_TAG"
