version: 2.1
orbs:
  node: circleci/node@3.0.0

workflows:
  lint_test_web:
    jobs:
      - lint_test_web:
            filters:
                  branches:
                        ignore:
                            - master
                            - project
      - cloc:
            filters:
                  branches:
                        ignore:
                            - master
                            - project

  lint_test_server:
      jobs:
      - lint_test_server:
            filters:
                  branches:
                        ignore: master

  deploy_prod:
      jobs:
      - deploy_prod:
            filters:
                  tags:
                        only: /[Vv]([0-9]{1,2}\.){2}[0-9]+/
                  branches:
                        ignore: /.*/

  deploy_docs_server:
      jobs:
      - deploy_docs_server:
            filters:
                branches:
                    only: master


jobs:
  cloc:
    docker:
        - image: circleci/node:12.18.3
    working_directory: ~/repo
    steps:
        - checkout
        - run:
              name: Count Web
              command: cd web && npx cloc src

  lint_test_web:
    docker:
        - image: circleci/node:12.18.3
    working_directory: ~/repo
    steps:
        - checkout
        - run:
              name: Install Dependencies
              command: cd web && npm ci
        - run:
              name: Run Linter
              command: cd web && npm run lint
        - run:
              name: Run Tests
              command: cd web && npm run test
        - run:
              name: Run Build
              command: cd web && npm run build

  lint_test_server:
    docker:
      - image: cimg/rust:1.58
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Remove Fast Build Shit
          command: rm -rf .cargo
      - run:
          name: Install Open-SSL
          command: sudo apt update; sudo apt install pkg-config libssl-dev
      - run:
          name: Install Stable
          command: rustup toolchain add stable
      - restore_cache:
          keys:
            - cache-{{ checksum "Cargo.toml" }} - {{ checksum ".circleci/config.yml" }}
      - run:
          name: Run Build
          command: cargo +stable build --release
      - save_cache:
          key: cache-{{ checksum "Cargo.toml" }} - {{ checksum ".circleci/config.yml" }}
          paths:
            - target
      - run:
          name: Run Clippy
          command: cargo +stable clippy --release
      - run:
          name: Run Test
          command: cargo +stable test --release

  deploy_prod:
      docker:
            - image: circleci/node:12.18.3
      working_directory: ~/repo
      steps:
            - checkout
            - run:
                  name: Remove Fast Build Shit
                  command: rm -rf .cargo
            - setup_remote_docker:
                  docker_layer_caching: true
                  version: 20.10.7
            - run:
                  name: Docker Login
                  command: docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run:
                  name: Build Container
                  command: docker build -t watsom27/stackk:server-$CIRCLE_TAG -f Dockerfile.server --build-arg API_KEY="$API_KEY" --build-arg AUTH_DOMAIN="$AUTH_DOMAIN" --build-arg PROJECT_ID="$PROJECT_ID" --build-arg STORAGE_BUCKET="$STORAGE_BUCKET" --build-arg MESSAGE_SENDER_ID="$MESSAGE_SENDER_ID" --build-arg APP_ID="$APP_ID" --build-arg APP_VERSION="$CIRCLE_TAG" --build-arg REPORTING_TOKEN="$REPORTING_TOKEN" .
            - run:
                  name: Push To Repository
                  command: docker push watsom27/stackk:server-$CIRCLE_TAG
            - run:
                  name: Print Version Number
                  command: echo "New Container Version - $CIRCLE_TAG"

  deploy_docs_server:
    docker:
      - image: cimg/rust:1.58
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Remove Fast Build Shit
          command: rm -rf .cargo
      - run:
          name: Install Open-SSL
          command: sudo apt update; sudo apt install pkg-config libssl-dev
      - restore_cache:
          keys:
            - cache-{{ checksum "Cargo.toml" }} - {{ checksum ".circleci/config.yml" }}
      - run:
          name: Cargo Doc
          command: cargo doc
      - save_cache:
          key: cache-{{ checksum "Cargo.toml" }} - {{ checksum ".circleci/config.yml" }}
          paths:
            - target
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Container
          command: docker build -t watsom27/stackk:docs -f Dockerfile.docs .
      - run:
          name: Push To Repository
          command: docker push watsom27/stackk:docs
      - run:
          name: Deploy New Image
          command: curl -X POST -k $WEBHOOK_URL
